apiVersion: v1
kind: Service
metadata:
  name: ilc-hello-service
  labels:
    name: ilc-hello
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    name: ilc-hello